baseURL = "http://example.com/"
languageCode = "en-us"
title = "Resto Hugo - Port of resto theme for hugo"
theme = "resto-hugo"

githubName = "mariesumalee"

copyright = "&copy 2021 Resto Hugo" # HTML tags supported
googleAnalytics = "UA-123-45"
disqusShortname = "yourdiscussshortname"

# Theme specific configuration
[params]
logo = "img/logo.png"
enableDisqus = true # enable / disable comments for blog posts
enableGA = true # enable / disable google analytics
heroText = "We Love <br> Delicious Real Foods !"
footerText = "This area supports HTML code. Text can be edited with <code>footerText</code> value in config.toml"
facebook = "https://facebook.com"
twitter = "https://twitter.com"
instagram = "https://instagram.com"


[[module.imports]]
    path = "[[module.imports]]
    path = "github.com/craftsmandigital/markdown-content-repo"
    disabled = false

    [[module.imports.mounts]]
    source = "testing-hugo-modules"
    target = "content/new-stuff"
