[build] 
  publish = "public"
  command = "hugo"
  
  [build.environment]
  HUGO_VERSION = "0.88.1"
  HUGO_BASEURL = "/"

[context.production.environment]
  HUGO_VERSION = "0.88.1" # if older, use format: 0.53 (no trailing zero)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.88.1"# if older, use format: 0.53 (no trailing zero)

[context.deploy-preview.environment]
  HUGO_VERSION = "0.88.1"
